apiVersion: apps/v1
kind: Deployment
metadata:
  name: crop-recommendation-model
spec:
  selector:
    matchLabels:
      app: crop-recommendation-model

  replicas: 3
  template:
    metadata:
      labels:
        app: crop-recommendation-model
    spec:
      containers:
        - name: crop-recommendation-model
          image: uk.icr.io/nikhil/crop-recommendation-model
          ports:
            - containerPort: 8000